#!/usr/bin/env python3
"""Cluster low-scoring semantic-eval pairs into a W-spec stub.

Usage:
    python3 scripts/cluster_low_scoring.py \
        --input golden_sets/semantic_eval_by_context/*.json \
        --include-tier1 golden_sets/semantic_eval_post_w17_w18.json \
        --output knowledge/wkmigrate-fix-spec-W20-auto.md

Groups low-scoring (<0.7) pairs by failure pattern found in the judge's
`reasoning` field. Writes a markdown spec ready for /wkmigrate-autodev
consumption.
"""

from __future__ import annotations

import argparse
import glob
import json
import re
from collections import defaultdict
from pathlib import Path


# Heuristic pattern detectors — each returns True if the reasoning matches.
# Order matters: more specific patterns should come first.
PATTERNS: list[tuple[str, re.Pattern]] = [
    ("firstRow_flattening", re.compile(r"firstRow|first.row|first row", re.IGNORECASE)),
    ("type_coercion_missing", re.compile(r"coercion|TypeError|type error|string > int|string.* vs.*int", re.IGNORECASE)),
    ("variables_taskkey_naming", re.compile(r"set_variable_|variables\(\).*taskKey|set_variable.*variable", re.IGNORECASE)),
    ("json_parse_assumption", re.compile(r"json\.loads.*assume|parse.*JSON|json string", re.IGNORECASE)),
    ("missing_null_handling", re.compile(r"null handling|KeyError|None handling|missing.*field", re.IGNORECASE)),
    ("division_semantics", re.compile(r"integer division|float division|//.*vs.*/|div\(\)", re.IGNORECASE)),
    ("nesting_order", re.compile(r"nesting|evaluation order|precedence", re.IGNORECASE)),
    ("activity_output_structure", re.compile(r"activity.*output.*structure|output.*dict|task.*value", re.IGNORECASE)),
]


def detect_patterns(reasoning: str) -> list[str]:
    """Return all pattern names that match the reasoning string."""
    found = []
    for name, pat in PATTERNS:
        if pat.search(reasoning):
            found.append(name)
    return found or ["uncategorized"]


def load_eval_file(path: Path) -> tuple[str, list[dict]]:
    """Return (context, low_scoring_pairs) from a semantic-eval JSON."""
    with open(path) as fp:
        data = json.load(fp)
    context = data.get("context", path.stem)
    low = data.get("low_scoring", [])
    return context, low


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-glob", required=True,
                        help="Glob for semantic-eval JSON files (e.g., golden_sets/semantic_eval_by_context/*.json)")
    parser.add_argument("--include", action="append", default=[],
                        help="Additional individual JSON files to include (can be repeated)")
    parser.add_argument("--output", required=True, help="Output markdown spec path")
    args = parser.parse_args()

    files = [Path(p) for p in glob.glob(args.input_glob)]
    files += [Path(p) for p in args.include if Path(p).exists()]

    if not files:
        print(f"No input files matched: {args.input_glob}")
        return 2

    print(f"Reading {len(files)} eval files...")

    # cluster_key → list of {context, adf_expression, python_code, score, reasoning}
    clusters: dict[str, list[dict]] = defaultdict(list)
    total_low = 0

    for f in files:
        context, low = load_eval_file(f)
        for pair in low:
            total_low += 1
            reasoning = pair.get("reasoning", "")
            patterns = detect_patterns(reasoning)
            for p in patterns:
                clusters[p].append({
                    "context": context,
                    "adf_expression": pair.get("adf_expression", ""),
                    "python_code": pair.get("python_code", ""),
                    "category": pair.get("category", ""),
                    "score": pair.get("score", 0.0),
                    "reasoning": reasoning[:500],
                })

    # Sort clusters by size, skip uncategorized if small
    sorted_clusters = sorted(clusters.items(), key=lambda kv: -len(kv[1]))

    # Write spec
    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# wkmigrate Fix Spec: W-20+ Auto-Generated From Semantic-Eval Clusters",
        "",
        "> Auto-generated by `scripts/cluster_low_scoring.py` from semantic-eval results.",
        "> Each cluster below is a failure pattern matched by heuristic regex on the LLM judge's reasoning text.",
        "> Review each cluster; promote clear ones to W-IDs before running /wkmigrate-autodev.",
        "",
        f"**Total low-scoring pairs (< 0.7):** {total_low}",
        f"**Clusters identified:** {len(sorted_clusters)}",
        "",
        "## Clusters (sorted by size)",
        "",
    ]

    for cluster_name, pairs in sorted_clusters:
        if len(pairs) < 2 and cluster_name == "uncategorized":
            continue  # Skip tiny uncategorized clusters
        lines.append(f"### `{cluster_name}` ({len(pairs)} pairs)")
        lines.append("")
        # Top 3 samples by lowest score
        top = sorted(pairs, key=lambda p: p["score"])[:3]
        lines.append("**Sample low-scoring pairs:**")
        for i, p in enumerate(top, 1):
            lines.append(f"")
            lines.append(f"**{i}. [{p['context']}, {p['category']}, score={p['score']}]**")
            lines.append(f"- ADF: `{p['adf_expression']}`")
            lines.append(f"- Python: `{p['python_code'][:200]}`")
            lines.append(f"- Reasoning: {p['reasoning'][:300]}")
        lines.append("")
        # Affected contexts
        contexts_affected = sorted(set(p["context"] for p in pairs))
        lines.append(f"**Contexts affected:** {', '.join(contexts_affected)}")
        lines.append("")
        # Categories affected
        categories_affected = sorted(set(p["category"] for p in pairs))
        lines.append(f"**Categories affected:** {', '.join(categories_affected)}")
        lines.append("")
        lines.append("---")
        lines.append("")

    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out} with {len(sorted_clusters)} clusters covering {total_low} low-scoring pairs.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
